ALTER TABLE "Product"
  ADD COLUMN IF NOT EXISTS "hasSize" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "hasColor" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "hasDimensions" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "ProductVariant"
  ALTER COLUMN "size" SET DEFAULT '',
  ADD COLUMN IF NOT EXISTS "dimensions" TEXT;
